Update programmes to more closely align with vilbli
NDLANO/ndla-frontend pull request #1089
Opened 2022-08-29 12:41 UTC by Jonas-C

Hvis vi behandler program-strukturen på https://www.vilbli.no/nb/nb/no som en slags fasit passer dette bedre enn vårt nåværende oppsett, samtidig som at alle kategoriseringer får et eksplisitt navn.

2022-11-02 09:42 UTC, ghveem reviewed
Likar dette ganske bra. 
Men dette vil føre til dobbelt opp med kategori + fag med namn Yrkesfaglig fordypning.

2022-11-02 09:42 UTC, ghveem commented on src/data/programmes.ts
> +            name: {
Fint!

2022-11-21 14:11 UTC, ghveem requested changes
Har diskutert med @johannesnag. Me kan gjerne ta inn det som kalles felles programfag, men då vil me at YFF ALLTID er eit felles programfag, i staden for å få ei eiga overskrift.
Det ser ikkje ut til å skape problem.

2022-11-22 07:56 UTC, gunnarvelle commented on src/data/programmes.ts
> +            name: {
Så fjerne denne overskrifta altså?

2022-11-22 07:59 UTC, gunnarvelle commented
Burde kanskje endre engelske navn her?

2022-11-22 09:08 UTC, ghveem commented on src/data/programmes.ts
> +            name: {
Ja, me juksar og flytter faget _Yrkesfaglig fordypning_ til gruppa/overskrift _Felles programfag._ 
I staden for faget _Yrkesfaglig fordypning_ under gruppa/overskrifta _Yrkesfaglig fordypning_

2022-11-22 09:24 UTC, ghveem approved these changes
Ser supert ut.

2022-11-22 10:44 UTC, merged