Landing page for subfolders
NDLANO/ndla-frontend pull request #1447
Opened 2023-08-08 11:01 UTC by katrinewi

fixes https://github.com/NDLANO/Issues/issues/3649

Viser landingsside for subfolders i min ndla og!

2023-08-08 12:33 UTC, gunnarvelle commented
Støtter denne fleire nivå av undermapper?

2023-08-09 07:01 UTC, gunnarvelle commented
Eg ser ikkje heilt problemet med navigasjon. For meg ser det ut som om det skjer akkurat som eg hadde forventa.

2023-08-09 08:56 UTC, Jonas-C commented
Jeg og Gunnar har snakket med Hedvig. Inntil videre tror vi det er lurt at trykking på "pilen" ekspanderer mappestrukturen, mens trykking på lenken tar deg til ny side.

2023-08-10 10:11 UTC, katrinewi commented
Prøvde å skrive om arrowen til en button, men det ble endel krøll med stylingen .. Beholdt det sånn det var og oppdaterte sånn at man åpner/lukker med arrow og at man går til mappen ved å trykke på teksten

2023-08-10 10:33 UTC, gunnarvelle commented
Fremdeles noe som er litt ruskete. Om du har åpna en ressurs i delt mappe, og så velger undermappe så funker det fint. Men om du etterpå velger en ressurs så bytter du til ressurs som forventa, men menyen åpnes igjen. Du må så lukke menyen for å sjå ressursen.

2023-08-10 10:34 UTC, gunnarvelle commented
Kan testes på https://ndla-frontend-pr-1447.ndla.sh/folder/b8d194ca-78c2-4b50-9d2b-497774e8608e/b8d194ca-78c2-4b50-9d2b-497774e8608e/c018a429-7841-4390-ba8a-74f60fe5e9f2

2023-08-11 08:14 UTC, gunnarvelle approved these changes

2023-08-11 08:21 UTC, Jonas-C requested changes
Tror nok dessverre det må være en `div` rundt en `button` og en `link`

2023-08-11 13:16 UTC, Jonas-C approved these changes

2023-08-14 05:03 UTC, merged