E2e folder page
NDLANO/ndla-frontend pull request #1742
Opened 2024-02-06 09:35 UTC by MaPoKen

2024-02-06 09:39 UTC, MaPoKen commented on e2e/specs/authenticated/MyNDLAFolder.spec.ts
> +  await page.waitForTimeout(1000);
Delete av en folder blir såklart ikke borte på sekundet, så prøvde en del ting men dette var den som fungerte. Gjerne kom med forslag 👯

2024-02-09 13:37 UTC, rauboti requested changes
Kjørte noen runder igjennom:
- Alle tester kjører som normalt når jeg kun kjører 1 og 1
- Dersom jeg kjører MyNDLAFolder.spec.ts fila samla, fullfører alle tester som de skal
- Dersom jeg kjører hele authenticated-mappa, feiler alltid 1, men det er forskjellig hver gang og det er alltid på første linja som venter på og prøver finne Mine mapper-headingen.

Er det slik at beforeEach kjører 1 gang for hver test (og derfor åpner sida 8 ganger); finnes det kanskje en måte å åpne den kun en gang på slik at ikke hver test starter med å vente på sida? 🤔

2024-02-09 13:37 UTC, rauboti commented on e2e/specs/authenticated/MyNDLAFolder.spec.ts
> +  const name = "Vår sterke test mappe";
Sida denne ikke venter på en operasjon; kunne den vært definert på toppen av test-funksjonen (ryddigere)?

2024-02-13 08:08 UTC, rauboti commented
@MaPoKen Har testet litt videre på dette for deg. Som nevnt over, feilet 1-2 random queries på `await expect(page.getByRole("heading").getByText("Mine mapper")).toBeInViewport()` når jeg kjørte hele authenticated-mappa. Når jeg prøvde å kjøre flere ganger, fikk jeg det av og til te å skje om jeg kjørte hele `MyNDLAFolder.spec.ts` også, selv om observasjonen over var at det gikk fint. En og en test går fortsatt helt fint. Jeg testa to ting:
- Flytte den linja som feilet opp til beforeEach. Det hadde ingen merkbar effekt.
- Sette testid på elementet, og skrive linja om til `await expect(page.getByTestId("folder-Mine mapper")).toBeInViewport()`. Da feilet steget aldri for meg lenger (jeg har kjørt authenticated-mappa 5-6 ganger nå uten å få det til å skje).

Et par steder kan det fortsatt feile etter den endringa når jeg kjører igjennom, men på lignende som den som feila sist; f.eks. folderList konstanten i "can drag and drop folders"-testen; `const folderList = page.getByRole("list").filter({ has: page.locator('[data-type="list"]') });`
Jeg veit ikke om getByRole i seg selv er problemet, eller om problemet er kombinasjoner av selectorer / filters. Men kanskje, så lenge poenget kun er å verifisere at elementer er der, at test id er hakket bedre for å unngå flaky tester.

2024-02-27 13:56 UTC, rauboti approved these changes
Kjørt på nytt noen ganger, med workers satt i `playwright.config.ts`, og da fungerer alt.

2024-04-16 14:10 UTC, Jonas-C commented
Flaky!

2024-04-17 06:55 UTC, rauboti commented
Klarer ikke reprodusere det lokalt, men  ser ut til å være 3 flaky tester når integration tests kjører

>   3 flaky
>    [MyNdla specs] › specs/authenticated/MyNDLAFolder.spec.ts:119:1 › can share and unshare folder ─
>    [MyNdla specs] › specs/authenticated/MyNDLAFolder.spec.ts:170:1 › can go to shared folder page ─
>    [MyNdla specs] › specs/authenticated/MyNDLAFolder.spec.ts:191:1 › can edit folder name on list item

2024-05-28 13:01 UTC, rauboti approved these changes
Kjører fint både lokalt og ved push, ser det ut til.

2024-08-23 08:20 UTC, gunnarvelle commented
Eller denne? Skal det ferdigstilles eller lukkes?

2024-08-23 08:22 UTC, MaPoKen commented
Tenker jeg ferdig stiller men skal vente på at nytt design er inne

2025-04-14 09:51 UTC, katrinewi commented
Virker som noen av testene i MyNDLAFolder er flaky 🤔 Etter å ha kjørt 3 ganger:
<img width="333" alt="Skjermbilde 2025-04-14 kl  11 50 51" src="https://github.com/user-attachments/assets/c7437a02-d0bd-4ab7-a8da-6c7dd65143bf" />
<img width="329" alt="Skjermbilde 2025-04-14 kl  11 51 16" src="https://github.com/user-attachments/assets/0856f687-8b28-4af1-b436-08c7ad96d123" />
<img width="328" alt="Skjermbilde 2025-04-14 kl  11 51 33" src="https://github.com/user-attachments/assets/f198d4d5-2dee-48a1-b424-76f48ccd2293" />

2025-04-14 11:17 UTC, katrinewi approved these changes

2025-04-14 11:21 UTC, merged