E2E Arena
NDLANO/ndla-frontend pull request #1746
Opened 2024-02-07 12:26 UTC by MaPoKen

2024-02-07 13:10 UTC, rauboti requested changes

2024-02-07 13:10 UTC, rauboti commented on e2e/specs/authenticated/MyNDLAPost.spec.ts
> +test("can add comment", async ({ page }) => {
Ser ut som denne testen feiler når hele `authenticated`-blokka kjøres samtidig. Den funker fint når den kjøres alene eller når jeg kjører alle tester i MyNDLAPost, men 3/3 forsøk på å kjøre hele `authenticated` tyder på at den ikke får det til. Den feiler også på forskjellige steder (helt i starten 1 gang, og rett etter posten er postet minst 1 gang, registrerte ikke første). Så kanskje det er noe med antall mock responses som kjører samtidig.

2024-02-27 13:51 UTC, rauboti approved these changes
Når jeg setter workers i `playwright.config.ts` kjører alle igjennom som de skal, også på øverste nivå.

2024-04-17 11:25 UTC, Jonas-C commented on e2e/specs/authenticated/MyNDLATopic.spec.ts
> +  await harCheckpoint();
Trenger man virkelig så mange checkpoints?

2024-05-28 07:35 UTC, rauboti commented
Testene kjører fint i denne branchen. Men sida forrige master branch merge er 2 uker gammal, prøvde jeg merge inn master lokalt - og da gikk ikke alt like bra.

2024-08-23 08:20 UTC, gunnarvelle commented
Kan dette lukkes, eller skal det inn på et tidspunkt?

2024-08-23 08:22 UTC, MaPoKen commented
Venter egentlig kun på at vi får inn nytt design så skal jeg oppdatere de.

2025-02-12 13:52 UTC, closed without merging