Add filter to url
NDLANO/ndla-frontend pull request #543
Opened 2020-09-10 07:56 UTC by brdalsnes

Fixes NDLANO/Issues#2235

2020-09-10 11:32 UTC, gunnarvelle requested changes

2020-09-10 11:32 UTC, gunnarvelle commented on src/containers/SubjectPage/SubjectPage.jsx
> +    if (data?.subject) {
Bør vel sjekke at ikkje det er valgt et filter fra før. Det er kun dersom det ikkje er valgt filter at dette kan skje. Og det er ikkje gitt at det finnes filter på subject og då kan vi ikkje loope uendelig..

2020-09-10 12:11 UTC, gunnarvelle commented on src/containers/SubjectPage/SubjectPage.jsx
> +        search: `?filters=${data.subject.filters[0].id}`,
Er vi sikre på at subjet har filters?
```suggestion
        search: `?filters=${data.subject.filters?.[0]?.id}`,
```

2020-09-10 12:14 UTC, brdalsnes commented on src/containers/SubjectPage/SubjectPage.jsx
> +        search: `?filters=${data.subject.filters[0].id}`,
Er vi ikke? Da bør vi sikkert heller droppe å legge på parameter i det tilfellet

2020-09-10 12:18 UTC, brdalsnes commented on src/containers/SubjectPage/SubjectPage.jsx
> +    if (data?.subject?.filters && !getFiltersFromUrl(location)) {
Bør vi også `?.[0]?.id` etter filters eller kan vi være sikre på det?

2020-09-10 12:21 UTC, gunnarvelle commented on src/containers/SubjectPage/SubjectPage.jsx
> +    if (data?.subject?.filters && !getFiltersFromUrl(location)) {
Du kan kanskje skrive filters?.length > 0

2020-09-10 12:44 UTC, gunnarvelle commented on src/containers/SubjectPage/SubjectPage.jsx
> +    if (data?.subject?.filters?.length && !getFiltersFromUrl(location)) {
Er det slik at dersom length = 0 så er dette falsy?

2020-09-10 12:47 UTC, brdalsnes commented on src/containers/SubjectPage/SubjectPage.jsx
> +    if (data?.subject?.filters?.length && !getFiltersFromUrl(location)) {
Ja

2020-09-10 12:52 UTC, gunnarvelle commented
Ser ikkje heilt ut som om det fungerer. Sjekk https://ndla-frontend-pr-543.ndla.sh/subjects/subject:3/topic:1:179373/topic:1:170165/resource:1:168357

2020-09-10 12:54 UTC, gunnarvelle commented
Kan SSR påvirke dette?

2020-09-10 17:42 UTC, brdalsnes commented
Det har å gjøre med at endringen bare er lagt til i SubjectPage og ikke ResourcePage. Det enkleste er vel bare å legge til det samme der pluss eventuelt andre sider vi trenger det på

2020-09-10 18:08 UTC, gunnarvelle commented
Det er sant. Det funka når eg gikk inn på et fag. Bra. Då må vi legge det til på ResourcePage også.

2020-09-14 06:30 UTC, gunnarvelle commented
Funksjonaliteten er fin, men det er problemstillinger rundt filter som må avklares før vi tar dette inn i master. 
Filter som returneres på fag kjem i tilfeldig rekkefølge, og det vil sei at du kan risikere å få forskjellig kontekst for kvar gong en url vises. Og det at filter ikkje kan velges via gui lenger men er koda inn i urlene på forsida gjør at ndla kan opprette filter som ikkje er "synlige" og kan jobbe med fremtidig innhold, men dersom du kan få tilordna et slikt filter automatisk så er det uheldig. 
Eg har bedt prosjektleder hos ndla om å sjekke ut dette før vi fullfører funksjonaliteten.

2020-09-16 06:18 UTC, gunnarvelle approved these changes
Eventuelle problemer med synlighet på filter tas utenom dette.

2020-09-16 06:56 UTC, merged