Refactor masthead to ts
NDLANO/ndla-frontend pull request #755
Opened 2021-08-27 14:01 UTC by Jonas-C

2021-08-30 07:57 UTC, haattis approved these changes
LGTM 🙌

2021-08-30 08:16 UTC, gunnarvelle requested changes

2021-08-30 08:16 UTC, gunnarvelle commented on src/containers/Masthead/components/MastheadMenu.tsx
> -        <MastheadMenuModal onMenuExit={this.onMenuExit} ndlaFilm={ndlaFilm}>
Du kan ikkje fjerne denne. Om du velger emne i menyen så lukker ikkje menyen seg lenger.

2021-08-30 08:20 UTC, gunnarvelle commented on src/containers/Masthead/components/MastheadMenu.tsx
> -        <MastheadMenuModal onMenuExit={this.onMenuExit} ndlaFilm={ndlaFilm}>
Forresten. Eg tenkte feil her. Menyen lukker seg som den skal.

Men det er nokke feil med denne sida når du klikker deg fram til den https://ndla-frontend-pr-755.ndla.sh/subject:1:ca607ca1-4dd0-4bbd-954f-67461f4b96fc/topic:1:89f902cb-98f4-4acc-be79-d3e2f40a8bf1/topic:1:5bd0cbfd-14fe-4201-b1c7-baa4e1504b48/resource:46831ee6-48ab-4525-a483-21961291267f

2021-08-30 11:48 UTC, Jonas-C commented on src/containers/Masthead/components/MastheadMenu.tsx
> -        <MastheadMenuModal onMenuExit={this.onMenuExit} ndlaFilm={ndlaFilm}>
Veldig merkelig feil. Ser ut som at MathJax.typeset() feilet når man gikk inn på en side på nytt. Hvis man console-logget MathJax før typset ble kalt gikk alt fint. Endret det til typesetPromise, som så ut til å fikse det. Usikker på hvorfor.

2021-08-31 10:11 UTC, gunnarvelle approved these changes
Så lenge feilen med MAthJax fikses ellers, LGTM

2021-08-31 12:40 UTC, merged