Added ability to add and read filters to and from url, respectively
NDLANO/ndla-frontend pull request #856
Opened 2022-01-17 12:51 UTC by Jonas-C

Fixes https://github.com/NDLANO/Issues/issues/2954

Søkesiden har vist seg å være ganske vanskelig å jobbe med, men dette ser ut til å fungere. Har dog erfart at det fører til en god del rerendering. Kan godt hende vi burde tenke litt annerledes på søkesiden for å øke ytelsen.

Har ingen spesifikke steg for testing, men foreslår å prøve litt forskjellige kombinasjoner av filtrering på innholdstyper og ressurstyper.

2022-01-19 07:00 UTC, haattis requested changes
Ved åpning av lenke med filter på ressurs så vil søket alltid returnere alle resultater. Se feks [lenke](https://ndla-frontend-pr-856.ndla.sh/search?activeSubFilters=subject-material%3Aurn%3Aresourcetype%3Aguidance&query=s%C3%B8k&selectedFilters=subject-material). Filteret er riktig markert, men det skulle vært 32 resultater og ikke alle (687 resultater).

2022-01-19 12:33 UTC, gunnarvelle reviewed
Ser at parametre blir feks `activeSubFilters=tasks-and-activities%3Aurn%3Aresourcetype%3Aexperiment&query=&selectedFilters=tasks-and-activities`. Her er tasks-and-activities gjentatt. Eller er det berre fordi subfilter har med parent i en kvasi-urn?
Du stripper jo urn:resourcetype fra parent. Om du gjør det samme fra sub vil du få en kortere url, om det er et poeng.

2022-01-19 12:33 UTC, gunnarvelle commented on src/containers/SearchPage/SearchInnerPage.jsx
> +  // const activeSubFiltersWithoutLeading = activeSubFilters.map((asf) => asf.substring(asf.indexOf(":urn:") -1));
Skal slettes?

2022-01-19 13:24 UTC, Jonas-C commented
> Ser at parametre blir feks `activeSubFilters=tasks-and-activities%3Aurn%3Aresourcetype%3Aexperiment&query=&selectedFilters=tasks-and-activities`. Her er tasks-and-activities gjentatt. Eller er det berre fordi subfilter har med parent i en kvasi-urn? Du stripper jo urn:resourcetype fra parent. Om du gjør det samme fra sub vil du få en kortere url, om det er et poeng.

Tanken var egentlig at ved å appende parent ville man kunne filtrere på ressurstyper med samme navn i forskjellige parents. Akkurat nå er f.eks "simulering" kun tilgjengelig under fagstoff, men det er jo ikke garantert at det alltid vil være tilfellet. Kunne eventuelt fjernet `urn:resource` og bare hatt `parent:child`, for deretter å fikse de i frontend.

2022-01-19 13:40 UTC, gunnarvelle commented
> Kunne eventuelt fjernet `urn:resource` og bare hatt `parent:child`, for deretter å fikse de i frontend.

Det viktigste er at det fungerer så det er ikkje så farlig.

2022-01-19 17:46 UTC, haattis commented
Ved klikk på filtre blir jeg umiddelbart scrollet til toppen nå, ellers fungerer det bra!

Om kortere urler er et stort pluss, og vi er sikre på at vi ikke kommer til å ha flere identiske subfiltre, kan man jo forenkle filtreringen ved å se bort fra parent:child-forholdet.

2022-01-20 06:17 UTC, gunnarvelle commented
Det vil nok ikkje skje at en får subtyper med samme id, men eg tenker det kan være greit å ha parent:child som parameter likevel. Det er ryddigst tenker eg.

2022-01-24 08:50 UTC, gunnarvelle commented
Valg for emne fungerer ikkje.

2022-01-24 09:15 UTC, gunnarvelle approved these changes
LGTM

2022-01-24 09:30 UTC, merged